### ISSUE TITLE
full parameters training with multi gpu

### ISSUE THREAD

**Issue by wangz1200** [moment-timeseries-foundation-model/moment#13] opened 2024-05-22 02:57 UTC
Hi, Thank you very much for disseminating openly your work and code.
I want to train the model with full parameters(T5 and Moment head). 
Could I tran it with multi gpus.
Thanks a lot.

**Comment by mononitogoswami** [comment] 2024-05-22 17:54
Hi,
Thanks for your interest in MOMENT. You can certainly train all the parameters of the model, even in a single GPU, depending on batch size. We trained MOMENT on one A6000 GPU with 49 GiB RAM (without multi GPU training) with a batch size of 1024 time series. More details can be found in the Reproducibility Statement in the [paper](https://arxiv.org/pdf/2402.03885).

When you download MOMENT, by default, the patch embedding layer and the transformer backbone (T5) are frozen. You can unfreeze them using the following code: 

  ```python

from momentfm import MOMENTPipeline

model = MOMENTPipeline.from_pretrained(
    "AutonLab/MOMENT-1-large", 
    model_kwargs={
        'task_name': 'reconstruction',
        'forecast_horizon': 192,
        'head_dropout': 0.1,
        'weight_decay': 0,
        'freeze_encoder': False, # Freeze the patch embedding layer. True by default.
        'freeze_embedder': False, # Freeze the transformer encoder. True by default.
        'freeze_head': False, # False by default
    },
)
```
You can certainly train the model on multiple GPUs using PyTorch modules such as [DDP](https://pytorch.org/tutorials/beginner/ddp_series_multigpu.html). Since we did not have to perform multi GPU training, we do not have code for this currently.   

Let us know if you have any more questions, and thanks again for your interest in MOMENT!

**Comment by wangz1200** [comment] 2024-05-23 09:19
Thank you for your reply. I appreciate it!

**Comment by mononitogoswami** [comment] 2024-05-23 19:32
Let us know how MOMENT works for you! For now, I'll close this issue. Feel free to open it again if you have any questions!

**Closed by mononitogoswami** 2024-05-23 19:32 UTC
Labels: documentation, question

**Comment by wangz1200** [comment] 2024-05-30 07:00
Thanks again for your reply.
Now,I had trained it with full parameters. And I saved the pretrained models(encoder mdoel and head mdoel).
Maybe my dataset is futures data, it is hard to forcast trend.
I want to combined with real data researching model ability.
